import { Language } from '@/types/models/code';

export const INTERVIEW_LANGUAGES = Object.freeze([
  Language.C,
  Language.C_PLUS_PLUS,
  Language.C_SHARP,
  Language.COBOL,
  Language.D,
  Language.DART,
  Language.ELIXIR,
  Language.ERLANG,
  Language.F_SHARP,
  Language.FORTRAN,
  Language.GO,
  Language.HASKELL,
  Language.JAVA,
  Language.JAVASCRIPT,
  Language.KOTLIN,
  Language.LISP,
  Language.LUA,
  Language.OBJECTIVE_C,
  Language.OCAML,
  Language.OCTAVE,
  Language.PASCAL,
  Language.PERL,
  Language.PHP,
  Language.PROLOG,
  Language.PYTHON_THREE,
  Language.RACKET,
  Language.RUBY,
  Language.RUST,
  Language.SCALA,
  Language.SWIFT,
  Language.TYPESCRIPT,
  Language.VISUAL_BASIC,
]);

export const ALGORITHM_LANGUAGES = Object.freeze([
  Language.C_PLUS_PLUS,
  Language.JAVA,
  Language.PYTHON,
  Language.PYTHON_THREE,
  Language.C,
  Language.C_SHARP,
  Language.JAVASCRIPT,
  Language.TYPESCRIPT,
  Language.PHP,
  Language.SWIFT,
  Language.KOTLIN,
  Language.DART,
  Language.GO,
  Language.RUBY,
  Language.SCALA,
  Language.RUST,
  Language.RACKET,
  Language.ERLANG,
  Language.ELIXIR,
]);

export const DATABASE_LANGUAGES = Object.freeze([
  Language.MY_SQL,
  Language.MS_SQL_SERVER,
  Language.ORACLE,
  Language.PANDAS,
  Language.POSTGRESQL,
]);

export const JAVASCRIPT_LANGUAGES = Object.freeze([
  Language.JAVASCRIPT,
  Language.TYPESCRIPT,
]);

export const SHELL_LANGUAGES = Object.freeze([Language.BASH]);

export const CONCURRENCY_LANGUAGES = Object.freeze([
  Language.C_PLUS_PLUS,
  Language.JAVA,
  Language.PYTHON,
  Language.PYTHON_THREE,
  Language.C,
  Language.C_SHARP,
]);

export const KATTIS_LANGUAGES = Object.freeze([
  Language.ADA,
  Language.ALGOL_68,
  Language.APL,
  Language.BASH,
  Language.C,
  Language.C_SHARP,
  Language.C_PLUS_PLUS,
  Language.COBOL,
  Language.LISP,
  Language.CRYSTAL,
  Language.D,
  Language.DART,
  Language.ELIXIR,
  Language.ERLANG,
  Language.F_SHARP,
  Language.FORTRAN,
  Language.GERBIL,
  Language.GO,
  Language.HASKELL,
  Language.JAVA,
  Language.JAVASCRIPT,
  Language.JULIA,
  Language.KOTLIN,
  Language.LUA,
  Language.MODULA_2,
  Language.NIM,
  Language.OBJECTIVE_C,
  Language.OCAML,
  Language.OCTAVE,
  Language.ODIN,
  Language.PASCAL,
  Language.PERL,
  Language.PHP,
  Language.PROLOG,
  Language.PYTHON,
  Language.PYTHON_THREE,
  Language.RUBY,
  Language.RUST,
  Language.SIMULA_67,
  Language.SMALLTALK,
  Language.SNOBOL,
  Language.SWIFT,
  Language.TYPESCRIPT,
  Language.VISUAL_BASIC,
  Language.ZIG,
]);
