import { Language } from 'types/models/code';

export const languagesMap: { [key: string]: string } = {
  [Language.C_PLUS_PLUS]: 'c_cpp',
  [Language.JAVA]: 'java',
  [Language.PYTHON]: 'python',
  [Language.PYTHON_THREE]: 'python',
  [Language.C]: 'c_cpp',
  [Language.C_SHARP]: 'csharp',
  [Language.JAVASCRIPT]: 'javascript',
  [Language.RUBY]: 'ruby',
  [Language.SWIFT]: 'swift',
  [Language.GO]: 'golang',
  [Language.SCALA]: 'scala',
  [Language.KOTLIN]: 'kotlin',
  [Language.RUST]: 'rust',
  [Language.PHP]: 'php',
  [Language.TYPESCRIPT]: 'typescript',
  [Language.RACKET]: 'scheme',
  [Language.ERLANG]: 'erlang',
  [Language.ELIXIR]: 'elixir',
  [Language.BASH]: 'sh',
  [Language.MY_SQL]: 'mysql',
  [Language.MS_SQL_SERVER]: 'sqlserver',
  [Language.ORACLE]: 'sql',
};
