name: Lint Commit Messages

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          helpURL: https://github.com/NUS-SoC-TIPS/frontend/blob/main/CONTRIBUTING.md
